USE master
GO

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'VatTuvaNhanCong')
    DROP DATABASE VatTuvaNhanCong
GO

CREATE DATABASE VatTuvaNhanCong
GO

USE VatTuvaNhanCong
GO

-- LOAI NHAN CONG
CREATE TABLE LOAINHANCONG (
    MaLoai NCHAR(10) PRIMARY KEY,
    TenLoai NVARCHAR(50) NOT NULL,
    MucLuongNgayCoBan MONEY NOT NULL,
    CONSTRAINT CK_LOAI_LUONG CHECK (MucLuongNgayCoBan > 0)
)
GO

-- CONG TRINH
CREATE TABLE CONGTRINH (
    MaCongTrinh NCHAR(10) PRIMARY KEY,
    TenCongTrinh NVARCHAR(100) NOT NULL,
    DiaDiem NVARCHAR(200) NOT NULL,
    NgayBatDau DATE NOT NULL,
    NgayDuKienKetThuc DATE NOT NULL,
    TrangThai NVARCHAR(50) DEFAULT N'Mới tạo' NOT NULL,
    CONSTRAINT CK_CT_NGAY CHECK (NgayDuKienKetThuc >= NgayBatDau)
)
GO

-- NHA CUNG CAP
CREATE TABLE NHACUNGCAP (
    MaNCC NCHAR(10) PRIMARY KEY,
    TenNCC NVARCHAR(100) NOT NULL,
    SoDienThoaiNCC VARCHAR(20) UNIQUE NOT NULL,
    DiaChi NVARCHAR(200) NOT NULL
)
GO

-- VAT TU
CREATE TABLE VATTU (
    MaVatTu NCHAR(10) PRIMARY KEY,
    TenVatTu NVARCHAR(100) NOT NULL,
    DonViTinh NVARCHAR(20) NOT NULL,
    DonGiaHienTai MONEY NOT NULL,
    CONSTRAINT CK_VT_GIA CHECK (DonGiaHienTai >= 0)
)
GO

-- DOI THI CONG
CREATE TABLE DOITHICONG (
    MaDoi NCHAR(10) PRIMARY KEY,
    TenDoi NVARCHAR(50) NOT NULL,
    MaNguoiQuanLy NCHAR(10) NULL
)
GO

-- NHAN CONG
CREATE TABLE NHANCONG (
    MaNhanCong NCHAR(10) PRIMARY KEY,
    HoTen NVARCHAR(50) NOT NULL,
    SoDienThoai NVARCHAR(20) UNIQUE NOT NULL,
    CCCD NVARCHAR(20) UNIQUE NOT NULL,
    TrangThaiLamViec NVARCHAR(50) DEFAULT N'Đang làm' NOT NULL,
    MaNguoiQuanLy NCHAR(10),
    MaDoi NCHAR(10) NOT NULL,
    MaLoai NCHAR(10) NOT NULL,

    CONSTRAINT FK_NC_DTC FOREIGN KEY (MaDoi) REFERENCES DOITHICONG(MaDoi),
    CONSTRAINT FK_NC_LOAI FOREIGN KEY (MaLoai) REFERENCES LOAINHANCONG(MaLoai)
)
GO

-- xử lý vòng
ALTER TABLE DOITHICONG
ADD CONSTRAINT FK_DTC_NC FOREIGN KEY (MaNguoiQuanLy) REFERENCES NHANCONG(MaNhanCong)
GO

-- KHO
CREATE TABLE KHO (
    MaKho NCHAR(10) PRIMARY KEY,
    TenKho NVARCHAR(50) UNIQUE NOT NULL,
    MaCongTrinh NCHAR(10) NOT NULL,

    CONSTRAINT FK_KHO_CT FOREIGN KEY (MaCongTrinh) REFERENCES CONGTRINH(MaCongTrinh)
)
GO

-- PHIEU NHAP
CREATE TABLE PHIEUNHAP (
    MaPhieuNhap NCHAR(10) PRIMARY KEY,
    NgayNhap DATE DEFAULT GETDATE() NOT NULL,
    NguoiGiao NVARCHAR(100) NOT NULL,
    NguoiNhan NVARCHAR(100) NOT NULL,
    MaKho NCHAR(10) NOT NULL,
    MaNCC NCHAR(10) NOT NULL,

    CONSTRAINT FK_PN_KHO FOREIGN KEY (MaKho) REFERENCES KHO(MaKho),
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
)
GO

-- PHIEU XUAT
CREATE TABLE PHIEUXUAT (
    MaPhieuXuat NCHAR(10) PRIMARY KEY,
    NgayXuat DATE DEFAULT GETDATE() NOT NULL,
    NguoiXuat NVARCHAR(100) NOT NULL,
    NguoiNhan NVARCHAR(100) NOT NULL,
    MaKho NCHAR(10) NOT NULL,

    CONSTRAINT FK_PX_KHO FOREIGN KEY (MaKho) REFERENCES KHO(MaKho)
)
GO

-- CHI TIET PHIEU NHAP
CREATE TABLE CHITIETPHIEUNHAP (
    MaPhieuNhap NCHAR(10),
    MaVatTu NCHAR(10),
    SoLuongNhap INT NOT NULL,
    DonGiaNhap MONEY NOT NULL,

    PRIMARY KEY (MaPhieuNhap, MaVatTu),
    CONSTRAINT CK_CTPN_SL CHECK (SoLuongNhap > 0),
    CONSTRAINT CK_CTPN_GIA CHECK (DonGiaNhap >= 0),

    CONSTRAINT FK_CTPN_PN FOREIGN KEY (MaPhieuNhap) REFERENCES PHIEUNHAP(MaPhieuNhap),
    CONSTRAINT FK_CTPN_VT FOREIGN KEY (MaVatTu) REFERENCES VATTU(MaVatTu)
)
GO

-- CHI TIET PHIEU XUAT
CREATE TABLE CHITIETPHIEUXUAT (
    MaPhieuXuat NCHAR(10),
    MaVatTu NCHAR(10),
    SoLuongXuat INT NOT NULL,
    MucDichSuDung NVARCHAR(200) NOT NULL,

    PRIMARY KEY (MaPhieuXuat, MaVatTu),
    CONSTRAINT CK_CTPX_SL CHECK (SoLuongXuat > 0),

    CONSTRAINT FK_CTPX_PX FOREIGN KEY (MaPhieuXuat) REFERENCES PHIEUXUAT(MaPhieuXuat),
    CONSTRAINT FK_CTPX_VT FOREIGN KEY (MaVatTu) REFERENCES VATTU(MaVatTu)
)
GO

-- PHAN CONG
CREATE TABLE PHANCONG (
    MaPhanCong NCHAR(10) PRIMARY KEY,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL,
    MaNhanCong NCHAR(10) NOT NULL,
    MaCongTrinh NCHAR(10) NOT NULL,

    CONSTRAINT CK_PC_NGAY CHECK (NgayKetThuc >= NgayBatDau),
    CONSTRAINT FK_PC_NC FOREIGN KEY (MaNhanCong) REFERENCES NHANCONG(MaNhanCong),
    CONSTRAINT FK_PC_CT FOREIGN KEY (MaCongTrinh) REFERENCES CONGTRINH(MaCongTrinh)
)
GO

-- CHAM CONG
CREATE TABLE CHAMCONG (
    MaChamCong INT IDENTITY(1,1) PRIMARY KEY,
    NgayChamCong DATE NOT NULL,
    SoCong FLOAT NOT NULL,
    GhiChu NVARCHAR(25) NULL,
    MaNhanCong NCHAR(10) NOT NULL,
    MaCongTrinh NCHAR(10) NOT NULL,

    CONSTRAINT CK_CC CHECK (SoCong >= 0),
    CONSTRAINT FK_CC_NC FOREIGN KEY (MaNhanCong) REFERENCES NHANCONG(MaNhanCong),
    CONSTRAINT FK_CC_CT FOREIGN KEY (MaCongTrinh) REFERENCES CONGTRINH(MaCongTrinh)
)
GO

-- THANH TOAN LUONG
CREATE TABLE THANHTOANLUONG (
    MaThanhToan NCHAR(10) PRIMARY KEY,
    KyLuong NVARCHAR(20) NOT NULL,
    TrangThaiThanhToan NVARCHAR(50) DEFAULT N'Chưa thanh toán' NOT NULL,
    MaNhanCong NCHAR(10) NOT NULL,

    CONSTRAINT FK_TT_NC FOREIGN KEY (MaNhanCong) REFERENCES NHANCONG(MaNhanCong)
)
GO

-- UNG LUONG
CREATE TABLE UNGLUONG (
    MaPhieuUng NCHAR(10) PRIMARY KEY,
    NgayUng DATE DEFAULT GETDATE() NOT NULL,
    SoTienUng MONEY NOT NULL,
    LyDo NVARCHAR(200) NOT NULL,
    MaNhanCong NCHAR(10) NOT NULL,

    CONSTRAINT CK_UL CHECK (SoTienUng > 0),
    CONSTRAINT FK_UL_NC FOREIGN KEY (MaNhanCong) REFERENCES NHANCONG(MaNhanCong)
)
GO

-- VU TIEN DAT
-- Nhập dữ liệu mẫu - Phát triển và Triển khai Kịch bản Dữ liệu mẫu 
